#!/usr/bin/env python3
"""Generate markdown tables for the five-model FedViM paper workflow."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DISPLAY_MODEL_NAMES = {
    "resnet101": "ResNet101",
    "efficientnet_v2_s": "EfficientNetV2-S",
    "mobilenetv3_large": "MobileNetV3-Large",
    "densenet169": "DenseNet169",
    "resnet50": "ResNet50",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate FedViM paper markdown tables.")
    parser.add_argument(
        "--summary-json",
        type=str,
        default="paper_tools/rerun_v1_results_summary.json",
        help="Summary JSON generated by collect_paper_results.py",
    )
    parser.add_argument(
        "--comparison-json",
        type=str,
        default="paper_tools/rerun_v1_results_full_comparison.json",
        help="Wide comparison JSON generated by collect_paper_results.py",
    )
    parser.add_argument(
        "--selected-json",
        type=str,
        default="paper_tools/rerun_v1_results_selected_models.json",
        help="Selected models JSON generated by collect_paper_results.py",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="paper_tools/tables",
        help="Directory for generated markdown tables.",
    )
    return parser.parse_args()


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def pct(value):
    return "-" if value is None else f"{value * 100:.2f}"


def rate(value):
    return "-" if value is None else f"{value * 100:.1f}%"


def integer(value):
    return "-" if value is None else str(int(value))


def display_model_name(name: str) -> str:
    return DISPLAY_MODEL_NAMES.get(name, name)


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    header_line = "| " + " | ".join(headers) + " |"
    sep_line = "| " + " | ".join(["---"] * len(headers)) + " |"
    body = ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join([header_line, sep_line, *body])


def build_full_table(rows: list[dict]) -> str:
    headers = [
        "Model",
        "ID Acc",
        "FedViM k",
        "ACT k",
        "ACT Compress",
        "FedViM Near",
        "ACT Near",
        "MSP Near",
        "Energy Near",
        "FedViM Far",
        "ACT Far",
        "MSP Far",
        "Energy Far",
    ]
    body = []
    for row in rows:
        body.append(
            [
                display_model_name(row["model_name"]),
                pct(row["id_accuracy"]),
                integer(row["fedvim_fixed_k"]),
                integer(row["act_k"]),
                rate(row["act_compression_rate"]),
                pct(row["fedvim_near_auroc"]),
                pct(row["act_near_auroc"]),
                pct(row["msp_near_auroc"]),
                pct(row["energy_near_auroc"]),
                pct(row["fedvim_far_auroc"]),
                pct(row["act_far_auroc"]),
                pct(row["msp_far_auroc"]),
                pct(row["energy_far_auroc"]),
            ]
        )
    return markdown_table(headers, body)


def build_selected_table(rows: list[dict]) -> str:
    headers = [
        "Model",
        "ID Acc",
        "FedViM k",
        "ACT k",
        "ACT Compress",
        "FedViM Near",
        "ACT Near",
        "ACT-FedViM vs FedViM",
        "FedViM Far",
        "ACT Far",
    ]
    body = []
    for row in rows:
        delta = row["act_minus_fedvim_near"]
        delta_text = "-" if delta is None else f"{delta * 100:+.2f}"
        body.append(
            [
                display_model_name(row["model_name"]),
                pct(row["id_accuracy"]),
                integer(row["fedvim_fixed_k"]),
                integer(row["act_k"]),
                rate(row["act_compression_rate"]),
                pct(row["fedvim_near_auroc"]),
                pct(row["act_near_auroc"]),
                delta_text,
                pct(row["fedvim_far_auroc"]),
                pct(row["act_far_auroc"]),
            ]
        )
    return markdown_table(headers, body)


def build_method_average_table(summary: dict) -> str:
    headers = ["Method", "Avg ID Acc", "Avg Near AUROC", "Avg Far AUROC", "Avg k", "Avg Compression"]
    body = []
    for method_name, values in summary["method_averages"].items():
        avg_k = values.get("act_k") if method_name == "ACT-FedViM" else values.get("fixed_k")
        body.append(
            [
                method_name,
                pct(values.get("id_accuracy")),
                pct(values.get("near_auroc")),
                pct(values.get("far_auroc")),
                integer(avg_k),
                rate(values.get("compression_rate")),
            ]
        )
    return markdown_table(headers, body)


def main() -> None:
    args = parse_args()
    summary = load_json(Path(args.summary_json))
    comparison_rows = load_json(Path(args.comparison_json))
    selected_rows = load_json(Path(args.selected_json))

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    full_table = build_full_table(comparison_rows)
    selected_table = build_selected_table(selected_rows)
    average_table = build_method_average_table(summary)

    summary_md = f"""# {summary['thesis_title']}

## 五模型完整结果

{full_table}

## 正文代表模型

选择原则：覆盖三种最关键情形，分别是轻量化部署案例、压缩与性能平衡案例，以及 fixed-k 失配纠偏案例。

{selected_table}

## 方法平均表现

{average_table}

## 摘要口径

- 实验范围：{", ".join(display_model_name(model) for model in summary["models"])}
- 正文代表模型：{", ".join(display_model_name(model) for model in summary["selected_models"])}
- ACT 相对 FedViM 的平均 Near-OOD AUROC 变化：{summary["act_vs_fedvim"]["avg_near_delta"] * 100:+.2f}
- ACT 相对 FedViM 的平均 Far-OOD AUROC 变化：{summary["act_vs_fedvim"]["avg_far_delta"] * 100:+.2f}
- ACT 平均子空间压缩率：{summary["act_vs_fedvim"]["avg_compression_rate"] * 100:.1f}%
"""

    (output_dir / "fedvim_five_model_full.md").write_text(full_table + "\n", encoding="utf-8")
    (output_dir / "fedvim_selected_models.md").write_text(selected_table + "\n", encoding="utf-8")
    (output_dir / "fedvim_method_averages.md").write_text(average_table + "\n", encoding="utf-8")
    (output_dir / "fedvim_paper_summary.md").write_text(summary_md, encoding="utf-8")

    print(f"Generated markdown tables in: {output_dir}")


if __name__ == "__main__":
    main()
