#!/usr/bin/env python3
"""Generate paper-ready figures for the five-model FedViM workflow."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate thesis figures from collected FedViM results.")
    parser.add_argument(
        "--summary-json",
        type=str,
        default="paper_tools/rerun_v1_results_summary.json",
        help="Summary JSON generated by collect_paper_results.py",
    )
    parser.add_argument(
        "--comparison-json",
        type=str,
        default="paper_tools/rerun_v1_results_full_comparison.json",
        help="Full comparison JSON generated by collect_paper_results.py",
    )
    parser.add_argument(
        "--selected-json",
        type=str,
        default="paper_tools/rerun_v1_results_selected_models.json",
        help="Selected models JSON generated by collect_paper_results.py",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="paper_tools/figures",
        help="Directory for generated figures.",
    )
    return parser.parse_args()


def load_json(path: str | Path):
    with Path(path).open("r", encoding="utf-8") as handle:
        return json.load(handle)


def save_figure(fig: plt.Figure, output_dir: Path, stem: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_dir / f"{stem}.png", dpi=300, bbox_inches="tight")
    fig.savefig(output_dir / f"{stem}.pdf", bbox_inches="tight")
    plt.close(fig)


def plot_method_comparison(rows: list[dict], output_dir: Path) -> None:
    models = [row["model_name"] for row in rows]
    x = np.arange(len(models))
    width = 0.2

    near_series = {
        "FedViM": [row["fedvim_near_auroc"] * 100 for row in rows],
        "ACT-FedViM": [row["act_near_auroc"] * 100 for row in rows],
        "MSP": [row["msp_near_auroc"] * 100 for row in rows],
        "Energy": [row["energy_near_auroc"] * 100 for row in rows],
    }
    far_series = {
        "FedViM": [row["fedvim_far_auroc"] * 100 for row in rows],
        "ACT-FedViM": [row["act_far_auroc"] * 100 for row in rows],
        "MSP": [row["msp_far_auroc"] * 100 for row in rows],
        "Energy": [row["energy_far_auroc"] * 100 for row in rows],
    }
    colors = {
        "FedViM": "#2F5597",
        "ACT-FedViM": "#C0504D",
        "MSP": "#9BBB59",
        "Energy": "#8064A2",
    }

    fig, axes = plt.subplots(1, 2, figsize=(15, 5), sharey=True)
    for idx, (label, values) in enumerate(near_series.items()):
        axes[0].bar(x + (idx - 1.5) * width, values, width=width, label=label, color=colors[label])
    axes[0].set_title("Near-OOD AUROC Comparison")
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(models, rotation=20)
    axes[0].set_ylabel("AUROC (%)")
    axes[0].set_ylim(70, 100)
    axes[0].grid(axis="y", linestyle="--", alpha=0.3)

    for idx, (label, values) in enumerate(far_series.items()):
        axes[1].bar(x + (idx - 1.5) * width, values, width=width, label=label, color=colors[label])
    axes[1].set_title("Far-OOD AUROC Comparison")
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(models, rotation=20)
    axes[1].set_ylim(70, 100)
    axes[1].grid(axis="y", linestyle="--", alpha=0.3)
    axes[1].legend(loc="lower left")

    fig.suptitle("FedViM Five-Model OOD Comparison", fontsize=14)
    fig.tight_layout()
    save_figure(fig, output_dir, "figure_1_method_comparison")


def plot_subspace_compression(rows: list[dict], output_dir: Path) -> None:
    models = [row["model_name"] for row in rows]
    x = np.arange(len(models))
    width = 0.35
    fixed_k = [row["fedvim_fixed_k"] for row in rows]
    act_k = [row["act_k"] for row in rows]
    compression = [row["act_compression_rate"] * 100 for row in rows]

    fig, ax1 = plt.subplots(figsize=(12, 5))
    ax1.bar(x - width / 2, fixed_k, width=width, label="FedViM fixed-k", color="#4F81BD")
    ax1.bar(x + width / 2, act_k, width=width, label="ACT-FedViM k", color="#C0504D")
    ax1.set_ylabel("Subspace Dimension k")
    ax1.set_xticks(x)
    ax1.set_xticklabels(models, rotation=20)
    ax1.grid(axis="y", linestyle="--", alpha=0.3)

    ax2 = ax1.twinx()
    ax2.plot(x, compression, color="#9BBB59", marker="o", linewidth=2, label="Compression Rate")
    ax2.set_ylabel("Compression Rate (%)")
    ax2.set_ylim(0, 100)

    handles1, labels1 = ax1.get_legend_handles_labels()
    handles2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(handles1 + handles2, labels1 + labels2, loc="upper right")
    ax1.set_title("Subspace Compression from FedViM to ACT-FedViM")
    fig.tight_layout()
    save_figure(fig, output_dir, "figure_2_subspace_compression")


def plot_selected_models(selected_rows: list[dict], output_dir: Path) -> None:
    models = [row["model_name"] for row in selected_rows]
    x = np.arange(len(models))
    width = 0.18

    fig, ax = plt.subplots(figsize=(12, 5))
    ax.bar(x - 1.5 * width, [row["fedvim_near_auroc"] * 100 for row in selected_rows], width=width, color="#4F81BD", label="FedViM Near")
    ax.bar(x - 0.5 * width, [row["act_near_auroc"] * 100 for row in selected_rows], width=width, color="#C0504D", label="ACT Near")
    ax.bar(x + 0.5 * width, [row["fedvim_far_auroc"] * 100 for row in selected_rows], width=width, color="#95B3D7", label="FedViM Far")
    ax.bar(x + 1.5 * width, [row["act_far_auroc"] * 100 for row in selected_rows], width=width, color="#E6B8B7", label="ACT Far")

    ax.set_xticks(x)
    ax.set_xticklabels(models)
    ax.set_ylabel("AUROC (%)")
    ax.set_ylim(75, 100)
    ax.grid(axis="y", linestyle="--", alpha=0.3)
    ax.legend(loc="lower right")
    ax.set_title("Paper-Selected Representative Models")
    fig.tight_layout()
    save_figure(fig, output_dir, "figure_3_selected_models")


def write_caption_notes(summary: dict, output_dir: Path) -> None:
    content = f"""# Figure Captions

## Figure 1

Five-model Near-OOD and Far-OOD AUROC comparison for `FedViM`, `ACT-FedViM`, `MSP`, and `Energy`.

## Figure 2

Comparison between the fixed-k FedViM subspace dimension and the ACT-selected subspace dimension. The average compression rate is {summary['act_vs_fedvim']['avg_compression_rate'] * 100:.1f}% across the five CNN backbones.

## Figure 3

Representative models selected for the thesis body according to ACT Near-OOD AUROC ranking with a maximum Near-OOD regression threshold of {summary['selection_rule']['max_near_drop'] * 100:.1f} percentage points.
"""
    (output_dir / "figure_captions.md").write_text(content, encoding="utf-8")


def main() -> None:
    args = parse_args()
    summary = load_json(args.summary_json)
    rows = load_json(args.comparison_json)
    selected_rows = load_json(args.selected_json)
    output_dir = Path(args.output_dir)

    plt.style.use("seaborn-v0_8-whitegrid")
    plot_method_comparison(rows, output_dir)
    plot_subspace_compression(rows, output_dir)
    plot_selected_models(selected_rows, output_dir)
    write_caption_notes(summary, output_dir)

    print(f"Generated figures in: {output_dir}")


if __name__ == "__main__":
    main()
